name: "Demonstração da pipeline"
on:
  push: 
    branches: [main]
  workflow_dispatch:
    
jobs:
  demonstrando-estrutura:
    name: "Demonstrar estrutura básica"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Mostrar estrutura .github/workflows
        run: |
          echo "== Listagem de arquivos =="
          ls -la .github/workflows
      