name: "Lab 03 - Branches e Paths"

### Executa apenas em push
on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - 'README.md'
    
jobs:
  push-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Informações do Push
        run: |
          echo "== Workflow disparado por PUSH =="
          echo "Commit: ${{ github.sha }}"
          echo "Autor: ${{ github.actor }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Repositório: ${{ github.repository }}"
      