name: "Lab 02 - Uso do cron"
on:
  schedule:
    - cron: '40 18 * * *'
    
jobs:
  schedule-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Informações do Schedule
        run: |
          echo "== Workflow disparado por SCHEDULE =="
          echo "Data atual: $(date)"
          echo "Hora UTC: $(date -u)"
          echo "Timezone: $(date +%Z)"
      